# serverless.yml

service: serverless-movies

plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-dynamodb-local

custom:
  tableName: 'movies-table-${self:provider.stage}'
  omdbApiParam: 'OMDBApiKey'
  wsgi:
    app: api.app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
  dynamodb:
    start:
      migrate: true
    stages:
      - dev
      - prod

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  apiKeys:
    - testKey
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ssm:GetParameter
      Resource:
        - "arn:aws:ssm:*:*:parameter/${self:custom.omdbApiParam}"
    - Effect: Allow
      Action: dynamodb:ListTables
      Resource: "*"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource:
        - { "Fn::GetAtt": ["MoviesDynamoDBTable", "Arn" ] }
  environment:
    MOVIES_TABLE: ${self:custom.tableName}
    OMDB_API_PARAM: ${self:custom.omdbApiParam}

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http:
          path: movies
          method: get
      - http:
          path: movies/{proxy+}
          method: get
      - http:
          path: movies
          method: post
          private: true
      - http:
          path: movies/{proxy+}
          method: put
          private: true
      - http:
          path: movies/{proxy+}
          method: delete
          private: true

resources:
  Resources:
    MoviesDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: title
            AttributeType: S
        KeySchema:
          -
            AttributeName: title
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 10
        TableName: ${self:custom.tableName}
